### ISSUE TITLE
Project fails its pre-commit checks

### ISSUE THREAD

**Issue by jiridanek** [rh-messaging-qe/yacfg#2]
https://github.com/jiridanek/YamlConfiger/runs/1021914139?check_suite_focus=true

```
pip install -r requirements.txt pre-commit
pre-commit run --all-files
```

There is multiple (test) issues. The yaml format checker fails, and the tox run for python 2.7 appears to be importing some Python 3.6 packages, for some reason... In any case, precommit is broken.

**Comment by enkeys** [comment]
This issue is no longer valid.
