### ISSUE TITLE
Adding --extra-properties option to allow yacfg to override generated results

### ISSUE THREAD

**Issue by gaohoward** [rh-messaging-qe/yacfg#24]
## Description
Due to yaml spec https://yaml.org/type/bool.html some values can be interpreted as boolean values
and therefore generated wrong results. To workaround this we can add an extra option to yacfg
so that the caller can pass in some 'extra' information as key-value set. Then we can add
an filter to check out on the extra properties and make proper overrides.

## Steps to Reproduce the Problem

As an example one can use a tune file that has one of the special values
like OFF and generated the result using yacfg. The OFF will get translated into False
in the final config.

## Expected Behavior
It should be kept as it is, ie OFF value should be OFF value and none else.

## Actual Behavior
The actual result will alter the user's original input. So we need fix that.

## Specifications

  - yacfg Version: 0.8.2
  - python Version: 2 and 3
  - Platform: all

## Notes

**Comment by enkeys** [comment]
@gaohoward Hey, our unit tests on these changes currently failing. We need to fix it first.
```
  tests/test_yacfg/test_generate.py::test_true_render_options FAILED       [  2%]
  tests/test_yacfg/test_generate.py::test_true_tuning_files FAILED         [  3%]
  tests/test_yacfg/test_generate.py::test_true_tuning_data FAILED          [  3%]
  tests/test_yacfg/test_generate.py::test_true_no_output_path_write_profile FAILED [  4%]
  tests/test_yacfg/test_generate.py::test_true_output_path_write_profile FAILED [  5%]
  tests/test_yacfg/test_generate.py::test_true_output_path FAILED          [  5%]
  tests/test_yacfg/test_generate.py::test_true_template FAILED             [  6%]
  tests/test_yacfg/test_generate.py::test_true_profile_template FAILED     [  7%]
  tests/test_yacfg/test_generate_core.py::test_true FAILED                 [  9%]
  tests/test_yacfg/test_generate_core.py::test_true_no_output_path_write_profile FAILED [  9%]
  tests/test_yacfg/test_generate_core.py::test_true_output_path_write_no_profile FAILED [ 10%]
  tests/test_yacfg/test_generate_core.py::test_true_output_path_write_profile FAILED [ 11%]
  tests/test_yacfg/test_generate_core.py::test_true_output_path FAILED     [ 11%]
  tests/test_yacfg/test_generate_core.py::test_true_template FAILED        [ 12%]
  tests/test_yacfg/test_generate_core.py::test_true_profile_template FAILED [ 13%]
```
